apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: restrictive
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restrictive
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated