apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: block-nginx
spec:
  readOnlyRootFilesystem: True
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'