apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: block-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: block-nginx
subjects:
- kind: ServiceAccount
  name: nginx
  namespace: default