apiVersion: constraints.gatekeeper.sh/v1beta1
kind: denyall
metadata:
  name: denyallpods
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    message: "ACCESS DENIED!"