apiVersion: v1
kind: Pod
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/app-armor-test: localhost/deny-all-writes
  labels:
    run: app-armor-test
  name: app-armor-test
spec:
  nodeName: worker1
  containers:
  - image: nginx
    name: app-armor-test